services:
  # Example compose setup with locally mounted hooks, migrations, and data
  pocketbase-example:
    image: ghcr.io/drakeapps/pocketbase:latest
    build:
      context: pocketbase
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./pocketbase/migrations:/pb/pb_migrations
      - ./pocketbase/hooks:/pb/pb_hooks
      - ./pocketbase/data:/pb/pb_data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  # Example compose setup with volume mounted hooks, migrations, and data
  pocketbase-volume-example:
    image: ghcr.io/drakeapps/pocketbase:latest
    build:
      context: pocketbase
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - pocketbase_data:/pb/pb_data
      - pocketbase_migrations:/pb/pb_migrations
      - pocketbase_hooks:/pb/pb_hooks
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  pocketbase_data:
  pocketbase_migrations:
  pocketbase_hooks:
